# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65b0c74ce719321e434802b8d3c439dc93524da51823453a64cd28306002b0882e63653053c4373d5fb6d663e41a8c9350e189d5f20ab26d76029c8c6f5c1e23

test:
  secret_key_base: c2f6c13ccab434f7b9da74eb5962527e3a301586d150c447cdebac83b2703953875416cffefbaffe53f5ad65ac03a2e824bfa7ab2ec8b1175519b506dd794929

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
